services:
  ibapi-service:
    network_mode: "host"
    container_name: ibapi-container
    build: ./ibapi-service
    volumes:
      - ./ibapi-service:/app

  sentinel-service:
    network_mode: "host"
    container_name: sentinel-container
    build: ./sentinel
    volumes:
      - ./sentinel:/app
    command: ["sh", "-c", "cd /app/cmd/server && fresh"]
    depends_on:
      - ibapi-service
